[{"ContainerToolsException.Message":"Сбой команды Docker с кодом завершения 1. #2 [internal] load build definition from Dockerfile #2 transferring dockerfile: 958B done #2 DONE 0.0s  #1 [internal] load .dockerignore #1 transferring context: 35B 0.0s done #1 DONE 0.0s  #3 [internal] load metadata for docker.io/library/ubuntu:18.04 #3 DONE 2.9s  #6 [internal] load build context #6 transferring context: 2B done #6 DONE 0.0s  #5 [stage-4 2/3] RUN apt update && apt upgrade -y && apt install redis-serv... #5 CACHED  #7 [stage-4 3/3] COPY redis.conf /etc/redis/redis.conf #7 ERROR: \"/redis.conf\" not found: not found  #4 [stage-4 1/3] FROM docker.io/library/ubuntu:18.04@sha256:fd25e706f3dea2a... #4 resolve docker.io/library/ubuntu:18.04@sha256:fd25e706f3dea2a5ff705dbc3353cf37f08307798f3e360a13e9385840f73fb3 done #4 CANCELED ------  > [stage-4 3/3] COPY redis.conf /etc/redis/redis.conf: ------ failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: \"/redis.conf\" not found: not found","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   в Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__12.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__176.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__26.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"#2 [internal] load build definition from Dockerfile\r\n#2 transferring dockerfile: 958B done\r\n#2 DONE 0.0s\r\n\r\n#1 [internal] load .dockerignore\r\n#1 transferring context: 35B 0.0s done\r\n#1 DONE 0.0s\r\n\r\n#3 [internal] load metadata for docker.io/library/ubuntu:18.04\r\n#3 DONE 2.9s\r\n\r\n#6 [internal] load build context\r\n#6 transferring context: 2B done\r\n#6 DONE 0.0s\r\n\r\n#5 [stage-4 2/3] RUN apt update && apt upgrade -y && apt install redis-serv...\r\n#5 CACHED\r\n\r\n#7 [stage-4 3/3] COPY redis.conf /etc/redis/redis.conf\r\n#7 ERROR: \"/redis.conf\" not found: not found\r\n\r\n#4 [stage-4 1/3] FROM docker.io/library/ubuntu:18.04@sha256:fd25e706f3dea2a...\r\n#4 resolve docker.io/library/ubuntu:18.04@sha256:fd25e706f3dea2a5ff705dbc3353cf37f08307798f3e360a13e9385840f73fb3 done\r\n#4 CANCELED\r\n------\r\n > [stage-4 3/3] COPY redis.conf /etc/redis/redis.conf:\r\n------\r\nfailed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: \"/redis.conf\" not found: not found"}]